### ISSUE TITLE
Add functionality to assign tasks to other users

### ISSUE THREAD

**Issue by Christian-Toney** [Makuwro/planzea#5]
```[tasklist]
### Tasks
- [ ] Add Makuwro users to projects
- [ ] Remove Makuwro users from projects
- [ ] Add project members to tasks
- [ ] Remove project members from tasks
```
