### ISSUE TITLE
Add the ability to use multiple subtask lists

### ISSUE THREAD

**Issue by Sudobeast** [Makuwro/planzea#59]
```[tasklist]
### Completion criteria
- [x] Add the ability to create new lists
- [x] Add the ability to delete lists
- [x] Add the ability to rename lists
- [x] Add the ability to reorder lists
- [x] Add the ability to reorder lists by buttons
```
